#!/bin/bash

set -euo pipefail

cp -r binder/Desktop ${HOME}/Desktop
chmod +x ${HOME}/Desktop/*.desktop

export CDL_DIR=$(dirname $(python -c "import cdl; print(cdl.__file__)"))

echo "export XDG_RUNTIME_DIR=${HOME}/.config/" >> ${HOME}/.bashrc
echo "export CDL_DIR=${CDL_DIR}" >> ${HOME}/.bashrc

ln -s ${CDL_DIR}/data/icons/DataLab.svg ~/.local/share/icons/DataLab.svg

ln -s ${CDL_DIR}/data/tests ${HOME}/Desktop/test_data

# Apply our Xfce settings
mkdir -p ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml
cp binder/xsettings.xml ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/
cp binder/xfce4-panel.xml ${HOME}/.config/xfce4/xfconf/xfce-perchannel-xml/

# For nbgitpuller
jupyter serverextension enable --py nbgitpuller --sys-prefix